de.connect2x.trixnity.core.model.EventId
de.connect2x.trixnity.core.model.RoomId
de.connect2x.trixnity.core.model.UserId
de.connect2x.trixnity.client.store.Room
de.connect2x.trixnity.clientserverapi.model.authentication.LoginType.SSO.IdentityProvider
de.connect2x.trixnity.client.store.RoomUser
de.connect2x.trixnity.client.verification.ActiveVerificationState